<?php 

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_622f0ac3a1a1b',
		'title' => 'Simple Post CTA',
		'fields' => array(
			array(
				'key' => 'field_622f0b0451db2',
				'label' => 'CTA Title text',
				'name' => 'cta_title_text',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'CTA Title',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_622f0b1451db3',
				'label' => 'CTA Button',
				'name' => 'cta_button',
				'type' => 'link',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
			),
			array(
				'key' => 'field_622f0b2751db4',
				'label' => 'CTA Background Color',
				'name' => 'cta_background_color',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'white-color' => 'White',
					'navy-color' => 'Navy',
					'blue-color' => 'Blue',
					'orange-color' => 'Orange',
					'cream-color' => 'Cream',
					'nude-color' => 'Nude',
				),
				'default_value' => 'navy-color',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_622f0b5a51db5',
				'label' => 'CTA Button Color',
				'name' => 'cta_button_color',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'white' => 'White',
					'navy' => 'Navy',
					'blue' => 'Blue',
					'orange' => 'Orange',
					'cream' => 'Cream',
					'nude' => 'Nude',
				),
				'default_value' => 'cream',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/cta',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

endif;